#
# TABLE STRUCTURE FOR: staff_edu_history
#

DROP TABLE IF EXISTS `staff_edu_history`;

CREATE TABLE `staff_edu_history` (
  `Staff_ID` char(5) NOT NULL COMMENT 'ID of staff for education\r\nhistory',
  `StaffEdu_Level` varchar(20) NOT NULL COMMENT 'Education level of staff:\r\nElementary, Secondary,\r\nBachelor, Master,\r\nDoctorate',
  `StaffEdu_Institution` varchar(50) NOT NULL COMMENT 'Education Institution of\r\nstaff in each level',
  `StaffEdu_Duration` tinyint(4) NOT NULL COMMENT 'Education duration of\r\nstaff in each institution',
  `StaffEdu_Grade` decimal(3,2) NOT NULL COMMENT 'GPA of staff',
  PRIMARY KEY (`Staff_ID`,`StaffEdu_Level`,`StaffEdu_Institution`),
  KEY `Staff_ID` (`Staff_ID`),
  CONSTRAINT `staff_edu_history_ibfk_1` FOREIGN KEY (`Staff_ID`) REFERENCES `staff_info` (`Staff_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0001', 'Doctorate', 'Port Raquel', 1, '0.79');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0001', 'Elementary', 'New Marcelinatown', 3, '1.87');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0002', 'Doctorate', 'Ruthbury', 2, '1.67');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0002', 'Elementary', 'Kaylintown', 1, '2.08');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0003', 'Bachelor', 'Douglashaven', 1, '1.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0003', 'Bachelor', 'New Clydeport', 1, '2.87');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0004', 'Doctorate', 'Karianeton', 4, '0.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0004', 'Elementary', 'New Frederic', 3, '2.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0005', 'Doctorate', 'Lake Heavenshire', 4, '2.39');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0005', 'Secondary', 'West Oniemouth', 3, '2.57');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0006', 'Master', 'Heidenreichhaven', 2, '1.37');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0006', 'Master', 'Nolanshire', 6, '3.30');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0007', 'Elementary', 'Nayelimouth', 1, '1.10');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0007', 'Master', 'Manteborough', 1, '3.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0008', 'Doctorate', 'New Hankfort', 6, '2.18');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0008', 'Master', 'Deckowmouth', 6, '0.32');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0009', 'Elementary', 'Edstad', 1, '0.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0009', 'Master', 'East Imeldaport', 2, '3.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0010', 'Bachelor', 'Abdielside', 3, '3.34');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0010', 'Elementary', 'East Princesstown', 1, '3.25');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0011', 'Doctorate', 'East Birdie', 4, '3.95');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0011', 'Master', 'South Mariannebury', 1, '2.48');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0012', 'Master', 'South Leonorburgh', 6, '0.30');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0012', 'Secondary', 'West Mozell', 4, '3.31');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0013', 'Secondary', 'South Carleeview', 4, '3.35');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0013', 'Secondary', 'Wintheiserbury', 4, '2.53');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0014', 'Secondary', 'Derickland', 6, '0.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0014', 'Secondary', 'East Reaganshire', 5, '2.70');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0015', 'Elementary', 'North Vernie', 6, '2.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0015', 'Master', 'Howardborough', 4, '1.43');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0016', 'Bachelor', 'South Loyberg', 3, '3.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0016', 'Elementary', 'Schadenton', 2, '3.92');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0017', 'Master', 'Lebsackshire', 5, '2.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0017', 'Secondary', 'South Garnet', 1, '3.43');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0018', 'Doctorate', 'Kulastown', 1, '3.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0018', 'Master', 'East Lilly', 2, '0.23');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0019', 'Secondary', 'Mohrton', 4, '1.41');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0019', 'Secondary', 'Port Margaretmouth', 3, '1.18');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0020', 'Bachelor', 'New Princeside', 1, '1.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('C0020', 'Doctorate', 'New Kristina', 3, '1.94');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0001', 'Elementary', 'West Elisebury', 4, '2.65');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0001', 'Secondary', 'Lake Janelle', 3, '1.92');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0002', 'Master', 'Port Brandyntown', 2, '0.42');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0002', 'Secondary', 'New Zora', 4, '3.41');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0003', 'Doctorate', 'Vonchester', 6, '1.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0003', 'Secondary', 'Port Ned', 4, '1.74');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0004', 'Master', 'North Alyciafurt', 1, '2.27');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0004', 'Master', 'West Oramouth', 5, '1.94');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0005', 'Bachelor', 'Ignacioburgh', 4, '0.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0005', 'Doctorate', 'Greenholtchester', 6, '2.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0006', 'Master', 'Kesslermouth', 4, '3.57');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0006', 'Secondary', 'Schowalterberg', 1, '0.69');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0007', 'Master', 'South Iva', 1, '0.21');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0007', 'Master', 'Torphybury', 5, '2.66');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0008', 'Bachelor', 'East Borisberg', 3, '2.00');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0008', 'Doctorate', 'West Antoniamouth', 6, '1.56');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0009', 'Bachelor', 'Codymouth', 1, '3.33');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0009', 'Doctorate', 'Genesisfurt', 3, '3.90');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0010', 'Doctorate', 'North Coralieland', 5, '2.90');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0010', 'Secondary', 'Haleyberg', 2, '2.95');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0011', 'Doctorate', 'North Jonathon', 1, '0.19');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0011', 'Master', 'Marcelofort', 6, '3.11');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0012', 'Doctorate', 'Heathcotefurt', 3, '3.09');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0012', 'Secondary', 'Swaniawskiview', 4, '2.02');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0013', 'Secondary', 'Nitzscheton', 1, '1.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0013', 'Secondary', 'Port Bradleystad', 5, '3.52');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0014', 'Master', 'East Paula', 5, '3.84');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0014', 'Master', 'East Yvonne', 3, '0.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0015', 'Doctorate', 'Abbottmouth', 1, '2.70');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0015', 'Elementary', 'Kubburgh', 2, '1.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0016', 'Bachelor', 'Port Terenceberg', 6, '2.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0016', 'Secondary', 'Paxtontown', 5, '2.38');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0017', 'Bachelor', 'Lake Judy', 1, '1.17');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0017', 'Elementary', 'Smithamtown', 1, '2.70');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0018', 'Doctorate', 'Stromanhaven', 4, '0.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0018', 'Elementary', 'New Kevon', 4, '2.12');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0019', 'Bachelor', 'Port Dino', 1, '3.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0019', 'Elementary', 'New Pamela', 6, '0.72');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0020', 'Doctorate', 'West Elnora', 5, '2.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0020', 'Elementary', 'Kreigerville', 3, '3.52');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0021', 'Bachelor', 'Funkburgh', 5, '2.01');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0021', 'Secondary', 'Arjunmouth', 2, '3.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0022', 'Bachelor', 'McLaughlinville', 3, '2.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0022', 'Elementary', 'Volkmanhaven', 3, '0.27');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0023', 'Doctorate', 'Port Jeffereyberg', 1, '1.55');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0023', 'Elementary', 'Gerlachton', 3, '2.70');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0024', 'Bachelor', 'O\'Keefeport', 2, '0.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0024', 'Secondary', 'Lake Austynmouth', 2, '1.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0025', 'Doctorate', 'Danielport', 3, '3.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0025', 'Elementary', 'East Alfonzochester', 4, '2.69');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0026', 'Elementary', 'East Sigurd', 3, '3.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0026', 'Elementary', 'Lake Ismaelmouth', 1, '1.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0027', 'Elementary', 'O\'Connellbury', 2, '0.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0027', 'Master', 'North Julia', 5, '1.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0028', 'Bachelor', 'West Ressie', 5, '1.75');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0028', 'Doctorate', 'North Terrence', 1, '1.40');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0029', 'Bachelor', 'North Sedrick', 4, '0.40');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0029', 'Secondary', 'North Nikoburgh', 4, '1.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0030', 'Master', 'East Ryleefurt', 1, '2.27');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0030', 'Master', 'Myraside', 1, '2.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0031', 'Bachelor', 'East Duanefurt', 6, '0.31');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0031', 'Doctorate', 'Port Oliverton', 5, '1.92');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0032', 'Doctorate', 'Mertzhaven', 4, '2.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0032', 'Doctorate', 'Myrtleview', 2, '3.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0033', 'Bachelor', 'North Leora', 6, '0.02');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0033', 'Master', 'Port Marty', 6, '3.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0034', 'Doctorate', 'Lake Ressie', 2, '0.10');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0034', 'Secondary', 'Satterfieldberg', 5, '1.34');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0035', 'Bachelor', 'Danikaton', 6, '2.17');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0035', 'Doctorate', 'Margarettown', 4, '2.85');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0036', 'Doctorate', 'Ceceliaside', 3, '0.67');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0036', 'Elementary', 'New Juwanview', 1, '3.49');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0037', 'Doctorate', 'Weberside', 6, '3.29');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0037', 'Secondary', 'Enochhaven', 5, '2.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0038', 'Doctorate', 'North Benedictville', 1, '0.30');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0038', 'Secondary', 'Robertsstad', 6, '2.15');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0039', 'Bachelor', 'Daytonborough', 5, '1.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0039', 'Master', 'Satterfieldborough', 2, '2.40');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0040', 'Bachelor', 'New Darienfurt', 5, '0.19');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0040', 'Master', 'Port Mark', 2, '0.53');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0041', 'Master', 'Taylorborough', 5, '2.79');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0042', 'Doctorate', 'Beahanton', 1, '1.01');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0043', 'Doctorate', 'South Donnie', 5, '1.04');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0044', 'Bachelor', 'Lake Amberton', 4, '0.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0045', 'Doctorate', 'Champlinport', 2, '1.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0046', 'Secondary', 'East Santina', 3, '1.22');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0047', 'Secondary', 'Bessiechester', 2, '1.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0048', 'Bachelor', 'Maybellmouth', 6, '3.02');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0049', 'Secondary', 'Westonside', 4, '0.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0050', 'Secondary', 'Wymanburgh', 6, '1.83');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0051', 'Secondary', 'North Mikelfort', 2, '3.60');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0052', 'Elementary', 'Willmsshire', 1, '3.80');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0053', 'Master', 'Anahiburgh', 3, '3.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0054', 'Bachelor', 'New Cole', 2, '0.33');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0055', 'Master', 'East Kingborough', 4, '3.67');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0056', 'Bachelor', 'North Antwan', 6, '2.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0057', 'Bachelor', 'South Marielaton', 6, '3.70');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0058', 'Bachelor', 'Port Helga', 3, '2.29');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0059', 'Elementary', 'East Antwanmouth', 2, '1.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0060', 'Doctorate', 'Corwinchester', 3, '2.84');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0061', 'Master', 'East Billiemouth', 2, '1.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0062', 'Elementary', 'Finnhaven', 3, '1.68');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0063', 'Secondary', 'Ferryside', 5, '3.83');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0064', 'Elementary', 'Port Alfredo', 2, '3.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0065', 'Secondary', 'South Amberstad', 3, '2.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0066', 'Doctorate', 'Satterfieldmouth', 2, '2.09');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0067', 'Bachelor', 'Fridamouth', 5, '0.05');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0068', 'Master', 'Port Darrick', 5, '1.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0069', 'Secondary', 'East Terenceside', 5, '2.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0070', 'Elementary', 'South Royburgh', 2, '0.30');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0071', 'Bachelor', 'East Rhiannon', 4, '2.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0072', 'Elementary', 'West Ethylton', 6, '0.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0073', 'Master', 'Elihaven', 5, '3.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0074', 'Doctorate', 'Port Keegan', 5, '0.15');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0075', 'Doctorate', 'Corwinberg', 3, '1.37');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0076', 'Secondary', 'Orinview', 5, '3.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0077', 'Master', 'Keeblerberg', 5, '0.22');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0078', 'Elementary', 'East Rosina', 3, '1.22');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0079', 'Bachelor', 'Angeloside', 6, '0.98');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0080', 'Secondary', 'Rutherfordmouth', 3, '2.85');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0081', 'Elementary', 'Goyetteburgh', 2, '2.50');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0082', 'Bachelor', 'North Dina', 4, '2.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0083', 'Doctorate', 'Lake Rose', 4, '2.98');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0084', 'Elementary', 'Lake Willard', 3, '3.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0085', 'Elementary', 'South Neomachester', 1, '1.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0086', 'Bachelor', 'East Corrineland', 6, '1.52');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0087', 'Bachelor', 'West Noble', 4, '1.29');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0088', 'Bachelor', 'East Kaylee', 6, '2.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0089', 'Master', 'East Erlingland', 6, '1.01');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0090', 'Elementary', 'Port Vickie', 4, '0.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0091', 'Bachelor', 'North Alize', 5, '0.74');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0092', 'Doctorate', 'Hauckhaven', 1, '2.71');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0093', 'Doctorate', 'Pasqualestad', 4, '2.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0094', 'Elementary', 'South Judah', 3, '1.52');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0095', 'Elementary', 'Rosemarychester', 5, '3.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0096', 'Doctorate', 'South Shana', 6, '1.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0097', 'Bachelor', 'North Anabel', 1, '2.42');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0098', 'Doctorate', 'Trompport', 3, '0.65');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0099', 'Doctorate', 'New Elliott', 5, '1.87');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('S0100', 'Master', 'Lake Rosella', 4, '0.07');


