# NOTE: Use first 15 staff

#
# TABLE STRUCTURE FOR: staff_edu_history
#

DROP TABLE IF EXISTS `staff_edu_history`;

CREATE TABLE `staff_edu_history` (
  `Staff_ID` char(5) NOT NULL COMMENT 'ID of staff for education\r\nhistory',
  `StaffEdu_Level` varchar(20) NOT NULL COMMENT 'Education level of staff:\r\nElementary, Secondary,\r\nBachelor, Master,\r\nDoctorate',
  `StaffEdu_Institution` varchar(50) NOT NULL COMMENT 'Education Institution of\r\nstaff in each level',
  `StaffEdu_Duration` tinyint(4) NOT NULL COMMENT 'Education duration of\r\nstaff in each institution',
  `StaffEdu_Grade` decimal(3,2) NOT NULL COMMENT 'GPA of staff',
  PRIMARY KEY (`Staff_ID`,`StaffEdu_Level`,`StaffEdu_Institution`),
  KEY `Staff_ID` (`Staff_ID`),
  CONSTRAINT `staff_edu_history_ibfk_1` FOREIGN KEY (`Staff_ID`) REFERENCES `staff_info` (`Staff_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST000', 'Doctorate', 'Beiermouth', 3, '2.12');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST000', 'Elementary', 'Kerlukeside', 6, '3.79');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST000', 'Elementary', 'West Jacquesland', 2, '3.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST001', 'Bachelor', 'East Isadorechester', 2, '3.41');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST001', 'Secondary', 'Citlallibury', 4, '1.57');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST001', 'Secondary', 'East Michele', 1, '1.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST002', 'Bachelor', 'New Carmela', 2, '0.30');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST002', 'Bachelor', 'Thompsonberg', 3, '0.45');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST002', 'Doctorate', 'New Mason', 6, '1.99');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST003', 'Doctorate', 'West Ottis', 1, '3.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST003', 'Elementary', 'Groverside', 1, '0.14');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST003', 'Master', 'Lowefurt', 1, '1.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST004', 'Elementary', 'Dachtown', 3, '3.14');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST004', 'Master', 'North Jeremieburgh', 4, '3.19');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST004', 'Master', 'South Eusebio', 1, '3.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST005', 'Bachelor', 'East Rossiemouth', 4, '3.82');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST005', 'Doctorate', 'East Estellmouth', 3, '3.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST006', 'Doctorate', 'South Isabell', 4, '1.42');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST006', 'Master', 'North Sandrineberg', 2, '2.92');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST007', 'Bachelor', 'Aryannafort', 1, '3.39');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST007', 'Secondary', 'East Helenamouth', 5, '3.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST008', 'Elementary', 'Nelsonfort', 4, '0.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST008', 'Master', 'Kraigborough', 6, '2.33');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST009', 'Bachelor', 'New Anthony', 1, '2.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST009', 'Master', 'East Alshire', 3, '3.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST010', 'Bachelor', 'West Clementberg', 4, '0.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST010', 'Elementary', 'Jennieshire', 5, '2.68');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST011', 'Bachelor', 'Lake Rico', 3, '3.69');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST011', 'Secondary', 'Gideonfurt', 5, '2.55');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST012', 'Bachelor', 'East Montymouth', 5, '3.38');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST012', 'Doctorate', 'East Weldonland', 1, '0.15');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST013', 'Doctorate', 'East Gunnar', 1, '0.71');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST013', 'Elementary', 'Jaredmouth', 3, '1.88');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST014', 'Doctorate', 'Rolfsonview', 4, '3.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST014', 'Master', 'East Abdiel', 1, '2.55');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST015', 'Bachelor', 'New Gabriellemouth', 6, '1.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST015', 'Doctorate', 'New Margarettown', 2, '0.38');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST016', 'Doctorate', 'West Meggie', 4, '3.98');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST016', 'Secondary', 'Judeside', 4, '2.66');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST017', 'Elementary', 'Omarishire', 6, '1.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST017', 'Master', 'Handton', 4, '0.13');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST018', 'Doctorate', 'Boscomouth', 6, '2.95');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST018', 'Secondary', 'Biankaton', 6, '0.31');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST019', 'Elementary', 'Lake Joshuah', 6, '2.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST019', 'Elementary', 'Rosaliabury', 2, '2.46');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST020', 'Bachelor', 'Lake Elise', 6, '2.99');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST020', 'Secondary', 'Lavernaport', 2, '0.65');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST021', 'Bachelor', 'Jennifermouth', 6, '2.82');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST021', 'Doctorate', 'Aminaville', 2, '2.64');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST022', 'Bachelor', 'East Leila', 2, '1.48');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST022', 'Master', 'East Oscarmouth', 2, '1.76');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST023', 'Elementary', 'Christopville', 4, '1.41');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST023', 'Master', 'Schmelertown', 1, '2.50');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST024', 'Bachelor', 'Amosberg', 2, '2.68');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST024', 'Doctorate', 'South Favianfort', 2, '3.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST025', 'Elementary', 'Brekkeborough', 4, '2.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST025', 'Elementary', 'Port Maegan', 2, '1.89');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST026', 'Doctorate', 'Weimannberg', 2, '0.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST026', 'Elementary', 'Kovacekhaven', 2, '0.90');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST027', 'Bachelor', 'Nolanmouth', 2, '2.25');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST027', 'Secondary', 'Heidenreichberg', 6, '3.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST028', 'Bachelor', 'Lake Alexisbury', 6, '1.08');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST028', 'Secondary', 'Laneyport', 1, '3.99');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST029', 'Bachelor', 'Port Devinchester', 4, '1.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST029', 'Elementary', 'Biankaview', 5, '1.11');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST030', 'Bachelor', 'Devinmouth', 6, '3.35');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST030', 'Master', 'North Laura', 5, '1.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST031', 'Doctorate', 'New Dorris', 1, '1.72');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST031', 'Elementary', 'North Elianeshire', 6, '3.31');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST032', 'Elementary', 'Floyberg', 4, '3.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST032', 'Secondary', 'Taliaville', 3, '3.02');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST033', 'Doctorate', 'Hettiechester', 4, '0.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST033', 'Doctorate', 'Homenickton', 3, '2.66');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST034', 'Secondary', 'East Kelley', 3, '3.20');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST034', 'Secondary', 'Lake Mara', 4, '1.58');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST035', 'Doctorate', 'North Ben', 4, '3.39');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST035', 'Elementary', 'Greenholtmouth', 6, '2.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST036', 'Master', 'East Brook', 1, '1.40');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST036', 'Secondary', 'South Ellisside', 5, '2.33');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST037', 'Doctorate', 'North Sister', 5, '2.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST037', 'Elementary', 'Ankundingfort', 2, '0.76');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST038', 'Bachelor', 'Gibsonview', 1, '1.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST038', 'Elementary', 'Port Jensenberg', 6, '1.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST039', 'Secondary', 'North Leonieland', 2, '1.71');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST039', 'Secondary', 'Syblehaven', 3, '2.01');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST040', 'Doctorate', 'New Jeffryburgh', 2, '0.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST040', 'Elementary', 'Reingerview', 2, '2.76');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST041', 'Doctorate', 'Collierborough', 1, '0.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST041', 'Master', 'Lake Jefferyborough', 1, '0.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST042', 'Master', 'Hodkiewiczchester', 1, '0.33');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST042', 'Secondary', 'Millerside', 4, '1.44');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST043', 'Doctorate', 'Cummingshaven', 5, '0.85');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST043', 'Doctorate', 'East Richmondfort', 6, '2.66');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST044', 'Doctorate', 'Lazaroville', 2, '0.41');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST044', 'Elementary', 'New Palma', 6, '3.53');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST045', 'Master', 'North Orlo', 5, '1.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST045', 'Secondary', 'Padbergport', 4, '3.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST046', 'Bachelor', 'Haleybury', 3, '2.88');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST046', 'Secondary', 'Ahmedshire', 5, '2.45');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST047', 'Doctorate', 'Jenkinsberg', 5, '0.68');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST047', 'Elementary', 'North Brennon', 4, '3.27');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST048', 'Bachelor', 'Port Halieland', 1, '3.00');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST048', 'Secondary', 'Matildeshire', 6, '2.10');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST049', 'Bachelor', 'Jarretmouth', 3, '1.32');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST049', 'Secondary', 'O\'Keefeland', 3, '2.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST050', 'Master', 'Grimesfurt', 5, '0.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST050', 'Secondary', 'Warrenside', 1, '2.64');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST051', 'Bachelor', 'Teaganhaven', 6, '2.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST051', 'Master', 'Ashleighview', 6, '3.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST052', 'Elementary', 'Port Marafort', 3, '3.59');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST052', 'Master', 'Leomouth', 3, '3.19');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST053', 'Bachelor', 'Gloverhaven', 4, '0.96');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST053', 'Master', 'Madysonmouth', 3, '1.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST054', 'Bachelor', 'Port Demario', 5, '2.62');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST054', 'Secondary', 'North Tracy', 5, '1.99');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST055', 'Master', 'Emelieton', 2, '1.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST055', 'Master', 'Gleasonport', 6, '3.60');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST056', 'Elementary', 'South Joesphside', 4, '3.65');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST056', 'Secondary', 'Keeblershire', 2, '0.81');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST057', 'Bachelor', 'South Ubaldo', 1, '1.08');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST057', 'Secondary', 'South Rhettmouth', 3, '1.13');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST058', 'Bachelor', 'West Saige', 2, '3.49');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST058', 'Doctorate', 'McDermottshire', 5, '2.07');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST059', 'Bachelor', 'Halvorsonhaven', 4, '2.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST059', 'Doctorate', 'Port Hank', 1, '2.28');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST060', 'Doctorate', 'Keenanborough', 5, '0.07');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST060', 'Master', 'Lake Derick', 4, '3.38');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST061', 'Bachelor', 'West Ike', 2, '1.91');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST061', 'Doctorate', 'East Jarred', 6, '2.10');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST062', 'Elementary', 'Andrefurt', 2, '1.69');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST062', 'Secondary', 'Lake Eldorahaven', 1, '3.19');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST063', 'Elementary', 'New Chester', 6, '2.63');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST063', 'Secondary', 'New Nestorton', 6, '1.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST064', 'Secondary', 'New Millerhaven', 1, '3.18');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST064', 'Secondary', 'Port Arturoborough', 4, '2.51');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST065', 'Doctorate', 'Marielaton', 2, '1.75');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST065', 'Master', 'Nolanhaven', 6, '2.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST066', 'Doctorate', 'Caseyhaven', 3, '1.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST066', 'Doctorate', 'Kamrenport', 3, '3.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST067', 'Master', 'Runolfssonbury', 4, '1.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST067', 'Secondary', 'Homenickfort', 6, '2.87');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST068', 'Bachelor', 'East Curtview', 2, '0.36');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST068', 'Master', 'Hermistonmouth', 2, '3.54');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST069', 'Master', 'Caterinatown', 3, '2.74');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST069', 'Master', 'North Jodie', 5, '0.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST070', 'Bachelor', 'North Halborough', 1, '3.52');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST070', 'Master', 'Lake Rowanfurt', 4, '3.57');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST071', 'Bachelor', 'Lake Cordie', 4, '1.26');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST071', 'Doctorate', 'Providencitown', 6, '3.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST072', 'Bachelor', 'South Georgette', 4, '1.31');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST072', 'Master', 'South Aniyahport', 3, '3.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST073', 'Master', 'Port Todland', 4, '3.37');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST073', 'Master', 'Rutherfordport', 4, '0.29');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST074', 'Doctorate', 'South Torrancemouth', 3, '0.02');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST074', 'Elementary', 'Kolbyton', 6, '2.85');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST075', 'Bachelor', 'Mohamedhaven', 6, '3.94');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST075', 'Bachelor', 'South Monserratside', 2, '1.47');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST076', 'Doctorate', 'Hicklebury', 6, '0.60');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST076', 'Elementary', 'South Robbie', 2, '0.94');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST077', 'Master', 'Destanyberg', 6, '1.61');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST077', 'Secondary', 'Greggchester', 5, '3.93');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST078', 'Secondary', 'Schultzview', 1, '2.80');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST078', 'Secondary', 'West Tina', 2, '1.14');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST079', 'Doctorate', 'Rexchester', 5, '2.45');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST079', 'Master', 'Lake Laneyton', 2, '3.83');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST080', 'Bachelor', 'Andreannefort', 1, '1.39');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST080', 'Bachelor', 'East Edport', 5, '2.73');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST081', 'Bachelor', 'North Ardith', 5, '0.66');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST081', 'Master', 'East Destiny', 3, '1.80');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST082', 'Doctorate', 'Lake Beulah', 4, '2.60');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST082', 'Elementary', 'Antwanbury', 5, '0.54');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST083', 'Bachelor', 'Lindgrenborough', 4, '1.24');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST083', 'Master', 'Port Ardellastad', 2, '2.78');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST084', 'Bachelor', 'New Tyriquetown', 3, '3.32');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST084', 'Doctorate', 'Carletontown', 4, '3.55');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST085', 'Master', 'Stromanburgh', 3, '0.09');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST085', 'Secondary', 'Lake Warrenton', 3, '2.85');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST086', 'Bachelor', 'Elinoreside', 3, '3.15');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST086', 'Elementary', 'North Julietfort', 5, '0.21');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST087', 'Bachelor', 'Rohanview', 3, '1.18');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST087', 'Master', 'Wilberville', 4, '0.44');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST088', 'Doctorate', 'Kovacekmouth', 1, '2.38');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST088', 'Secondary', 'Jadamouth', 6, '2.06');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST089', 'Doctorate', 'South Ray', 1, '2.12');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST089', 'Master', 'Lebsackfort', 1, '2.40');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST090', 'Bachelor', 'Lake Zachary', 6, '1.03');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST090', 'Doctorate', 'West Kianafurt', 5, '0.77');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST091', 'Bachelor', 'South Cheyannechester', 3, '3.11');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST091', 'Secondary', 'New Kiarraburgh', 3, '2.09');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST092', 'Bachelor', 'Clintview', 3, '2.86');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST092', 'Secondary', 'Valentinahaven', 6, '0.79');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST093', 'Bachelor', 'Schinnerside', 3, '0.37');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST093', 'Secondary', 'South Lacey', 4, '1.81');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST094', 'Bachelor', 'Silasside', 2, '1.98');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST094', 'Elementary', 'North Mae', 5, '0.32');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST095', 'Bachelor', 'Lake Anjali', 2, '2.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST095', 'Bachelor', 'New Tomasafurt', 2, '1.21');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST096', 'Bachelor', 'Herzogtown', 4, '4.00');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST096', 'Secondary', 'Stoltenbergmouth', 1, '2.16');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST097', 'Elementary', 'New Dejon', 6, '0.54');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST097', 'Secondary', 'North Neil', 3, '3.67');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST098', 'Doctorate', 'New Milford', 3, '0.32');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST098', 'Master', 'East Vernice', 2, '0.80');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST099', 'Bachelor', 'Lake Ignacio', 3, '3.08');
INSERT INTO `staff_edu_history` (`Staff_ID`, `StaffEdu_Level`, `StaffEdu_Institution`, `StaffEdu_Duration`, `StaffEdu_Grade`) VALUES ('ST099', 'Master', 'Schillerborough', 6, '0.85');


